### ISSUE TITLE
Write code to display loads using VTK glyphs.

### ISSUE THREAD

**Issue by lcpt** [lcpt/xc#14]
See code in the file
[test_vector_field02.py.zip](https://github.com/lcpt/xc/files/112529/test_vector_field02.py.zip)
![test_vector_field02](https://cloud.githubusercontent.com/assets/12873038/12722850/19582386-c907-11e5-9dcd-678db07c77ba.png)

**Comment by lcpt** [comment]
Implemented in LoadVectorField. There are some things to add:

- Scalar bar (see creaColorScaleBar in vtk_lut_field.py).
- Axes XYZ (see Axes.py).
- Corner annotations (see pruebaTexto.py.zip and search for an example of vtkCornerAnnotation).

[pruebaTexto.py.zip](https://github.com/lcpt/xc/files/195249/pruebaTexto.py.zip)

[Axes.py.zip](https://github.com/lcpt/xc/files/195208/Axes.py.zip)

**Comment by anaiortega** [comment]
To implement in LoadVectorField the option of representing loads on surface elements per unit area instead of the total load on the element

**Comment by lcpt** [comment]
Done!
