### ISSUE TITLE
get started with XC

### ISSUE THREAD

**Issue by berndhahnebach** [lcpt/xc#32]
Hi Luis, Hi Ana,

ist there some documentation to get started? I found https://github.com/anaiortega where are a lot of models. I'm looking for some simple example to get started. 

cheers bernd

**Comment by lcpt** [comment]
Hi Bernd.

We are writing some tutorials based on verificatio tests (they are all very simple). A draft of the fisrt one will be ready in two or three days.

Regards Luis.

**Comment by lcpt** [comment]
You ca find some documentation here:

https://lcpt.github.io/XCmanual/

And here https://codedocs.xyz/lcpt/xc/index.html (almost all of the C++ objects are already exposed to Python via boost.python) the corresponding Python functions are almos always obvious.

@anaiortega can you put some more information here?

Cheers.

**Comment by berndhahnebach** [comment]
Hi Luis,

I saw them both alredy. What I'm looking for is a simple expample how to set up geometry, a mesh, the constraints, the element type, run the solver, do some simple post processing.

Just to get a start. If I know this for a simple example than I will find all other stuff in thesdocumentations mentioned above, hopefully :-)

cheers bernd

**Comment by anaiortega** [comment]
These articles deal with several verification tests included in the verif directory, but not exactly a tutorial:

- Interaction diagrams (tests: test_diag_interaccion01.py to test_diag_interaccion06.py, interaction_diagram_mayavi.py)
http://www.xcengineering.xyz/blog_doc/2016_interact_diag/interactionDiagram.pdf

- Tension stiffening (tests: test_concrete02_02, test_smearedCracking_01.py to test_smearedCracking_06.py)
http://www.xcengineering.xyz/blog_doc/2017_tens_stiff/XCtensionStiffening.pdf

- Building according to Eurocode (https://github.com/anaiortega/XCmodels/tree/master/buildingEC2 , probably outdated)
http://www.xcengineering.xyz/blog_doc/2017_EC2building/EC2Building.pdf

- Vibrating string (test: test_string_under_tension.py)

http://www.xcengineering.xyz/blog_doc/2017_vibr_string/modes_vibrating_string_tension.pdf

- Prestressing (tests: test_layout3D_frictLoss_prestress_tendon.py, test_anchorageLoss_prestress_tendon_01.py, test_loss_prestress_units_01.py, test_anchorageLoss_prestress_tendon_03.py, test_layout2D_frictLoss_prestress_tendon.py, test_anchorageLoss_prestress_tendon_04.py, test_anchorageLoss_prestress_tendon_02.py, prestressed_concrete_section_02.py, prestressed_concrete_section_01.py)
http://www.xcengineering.xyz/blog_doc//2018_prestressing_partI/XC_prestressing.pdf

- Tensegrity (https://github.com/anaiortega/XCmodels/tree/master/tensegrity_prisms)
http://www.xcengineering.xyz/blog_doc/2017_tensegrity/XC_tensegrity_models.pdf

**Comment by anaiortega** [comment]
Sorry, upper-lower case misplaced in url :-)

http://www.xcengineering.xyz/blog_doc/2017_EC2Building/EC2building.pdf

**Comment by lcpt** [comment]
> Hi Luis,
> 
> I saw them both alredy. What I'm looking for is a simple expample how to put the pieces together. How to set up geometry, a mesh, the constraints, the element type, run the solver, do some simple post processing.
> 
> Just to get a start. If I know this for a simple example than I will find all other stuff in thesdocumentations mentioned above, hopefully :-)
> 
> cheers bernd

You can take a look here (meshing): xc/verif/tests/preprocessor/test_surface_meshing_01.py 

and here (tiny complete example without meshing):  xc/verif/tests/elements/truss_temperat.py

**Comment by anaiortega** [comment]
Well, let's take
https://github.com/anaiortega/XCmodels/tree/master/workingModel

a simpler model than the buildingE2 (probably outdated).

Perhaps you can follow the stream top-down by executing the scripts in the directory  'display'. For example

- display_mesh.py : shows the mesh. It calls the main script 'model_gen.py' (most of the functions are commented out in the script) that keeps the basic model data (geometry, loads, combinations, ...) and generates de mesh. 

- display_loads.py: calls the aforementioned 'model_gen.py' and 'loadStateData.py' which is only a script to configure scales, units, etc. for the representation on the loads defined in the model_gen.py script.

Up to here, files related to model generation. The others require to solve the FE problem, define the reinforcement, run limit state verifications, ... (a little longer, we'll try to make an introduction to that)

Cheers

**Comment by lcpt** [comment]
An example a bit more complete: xc/verif/tests/elements/shell/test_shell_mitc4_13.py

**Comment by lcpt** [comment]
I've updated some examples in verif so it's better if you make a pull.

Cheers.

**Comment by berndhahnebach** [comment]
great. Thanks for all the informations. I will try diving into it and give some feedback ... 

Bernd

**Comment by lcpt** [comment]
With pleasure!

**Comment by berndhahnebach** [comment]
https://github.com/anaiortega/XCmodels/issues
