### ISSUE TITLE
set distro name changes source

### ISSUE THREAD

**Issue by berndhahnebach** [lcpt/xc#39]
set distro name changes source code even if we gone make an out of source build. This is cumbersome if someone works with git and a distro diffrent than ubuntu. In orginal source the name is set to ubuntu and for every cmake run it is changed to debian for me. I need to git checkout the old file with ubuntu than to not change the code for a PR. But than on my machine there is a ubuntu but I'm on debian.

Do we really write the distro name in a file inside the sources? See https://github.com/lcpt/xc/blob/master/CMake/distro_name.txt and https://github.com/lcpt/xc/blob/master/CMake/get_distro_name.sh Is this used somewhere?

cheers bernd

**Comment by lcpt** [comment]
The idea was to use DISTRO_NAME inside CMake to generate binary packages (.deb, .rpm) with CPACK (see the last lines of CMakeLists.txt on each repository). After that, the results we obtained with CPACK in 2013 were a bit discouraging so we stopped trying.

Maybe we must separate the CPACK stuff... I'll take a look as soon as posible.

**Comment by berndhahnebach** [comment]
or just write some info and comment it and deactivate the set distro name. 

Bernd

**Comment by berndhahnebach** [comment]
btw, same applys for xc_basic and xc_utils

**Comment by lcpt** [comment]
I think I fixed it in all three repositories. I've put distro_name.txt in .gitignore to let each machine to create it locally. I've put apart the CPack stuff too. I'll get around to making changes when I can.

Cheers. Luis.

**Comment by berndhahnebach** [comment]
works great in all three repos for me :-)
